'use client';
import { useState } from 'react';
import { useParams } from 'next/navigation';
import { AppShell, Topbar } from '../../../../../components/AppShell';
import { OcclusionEditor } from '../../../../../components/OcclusionEditor';
import { isEnabled } from '../../../../../lib/config/feature-flags';
import { mediaService } from '../../../../../lib/services/media-service';
import { occlusionService, type OcclusionMask } from '../../../../../lib/services/occlusion-service';
export default function NewOcclusionPage() { const { deckId } = useParams<{ deckId: string }>(); const [noteId, setNoteId] = useState(''); const [url, setUrl] = useState(''); const [masks, setMasks] = useState<OcclusionMask[]>([]); const [message, setMessage] = useState(''); if (!isEnabled('occlusion')) return <AppShell><Topbar title="Oclusão" /><div className="card empty-state">Esta funcionalidade está desativada.</div></AppShell>; async function upload(e: React.ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; try { const asset = await mediaService.upload(file); if ('storage_key' in asset) setUrl((await mediaService.signedUrl(asset.storage_key)) ?? ''); setMessage('Imagem carregada. Desenhe as regiões na imagem.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Falha no upload.'); } } async function save() { try { await occlusionService.createNote({ noteId, masks }); setMessage(`Cartões de oclusão criados para o deck ${deckId}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Falha ao criar oclusão.'); } } return <AppShell><Topbar title="Nova oclusão de imagem" /><section className="card form"><label htmlFor="occlusion-note-id">ID da nota</label><input id="occlusion-note-id" value={noteId} onChange={(e) => setNoteId(e.target.value)} /><label className="sr-only" htmlFor="occlusion-image-upload">Selecionar imagem para oclusão</label><input id="occlusion-image-upload" type="file" accept="image/*" onChange={upload} />{url && <OcclusionEditor imageUrl={url} value={masks} onChange={setMasks} />}<button className="btn" onClick={() => void save()} disabled={!noteId || !masks.length}>Criar cartões Cloze</button><p role="status">{message}</p></section></AppShell>; }
