import { createClient, type Json } from '../supabase/client';
import { searchNotes, type SearchResponse } from './search-service';
export type McpTool = { name: string; description: string; parameters: Record<string, unknown> };
export type McpRequest = { jsonrpc: '2.0'; id: string; method: 'tools/list' | 'tools/call'; params?: { name?: string; arguments?: Record<string, unknown> } };
export type McpResponse<T = unknown> = { jsonrpc: '2.0'; id: string; result?: T; error?: { code: number; message: string } };
const TOOLS: McpTool[] = [{ name: 'search_notes', description: 'Busca notas do utilizador por texto ou similaridade semântica.', parameters: { query: 'string', limit: 'number', mode: 'semantic | lexical' } }, { name: 'create_note', description: 'Cria uma nota e os seus cartões de forma transacional.', parameters: { deck_id: 'string', fields: 'object', card_definitions: 'array', template_id: 'string?' } }];
function requestId() { return crypto.randomUUID(); }
export const mcpClient = { listTools(): McpTool[] { return TOOLS; }, async callTool(name: string, args: Record<string, unknown>): Promise<unknown> { const supabase = createClient(); if (name === 'search_notes') { const result = await searchNotes(String(args.query ?? ''), (args.mode === 'lexical' ? 'lexical' : 'semantic'), Number(args.limit ?? 20)); return result; } if (name === 'create_note') { const fields = args.fields; if (!args.deck_id || !fields || typeof fields !== 'object') throw new Error('MCP_CREATE_NOTE_INPUT_REQUIRED'); const { data, error } = await supabase.rpc('mcp_create_note', { p_deck_id: String(args.deck_id), p_fields: fields as Json, p_template_id: args.template_id ? String(args.template_id) : undefined, p_card_definitions: (args.card_definitions ?? []) as Json, p_source: 'mcp', p_request_id: requestId() }); if (error) throw error; return data; } throw new Error(`MCP_UNKNOWN_TOOL:${name}`); }, async handle(request: McpRequest): Promise<McpResponse> { try { if (request.method === 'tools/list') return { jsonrpc: '2.0', id: request.id, result: { tools: TOOLS } }; const name = request.params?.name; if (!name) throw new Error('MCP_TOOL_REQUIRED'); const result = await this.callTool(name, request.params?.arguments ?? {}); return { jsonrpc: '2.0', id: request.id, result }; } catch (error) { return { jsonrpc: '2.0', id: request.id, error: { code: -32000, message: error instanceof Error ? error.message : 'MCP_ERROR' } }; } } };
export async function mcpSearchNotes(query: string, limit = 20): Promise<SearchResponse> { return searchNotes(query, 'semantic', limit); }
