import { beforeEach, describe, expect, it, vi } from 'vitest';
import { AuthRequiredError, EdgeTimeoutError, RateLimitError, UnavailableError } from '../lib/services/http/errors';
const invoke = vi.fn(); const getSession = vi.fn();
vi.mock('../lib/supabase/client', () => ({ createClient: () => ({ auth: { getSession }, functions: { invoke } }) }));
const { invokeEdge } = await import('../lib/services/http/edge-client');
describe('invokeEdge', () => { beforeEach(() => { invoke.mockReset(); getSession.mockResolvedValue({ data: { session: { access_token: 'test' } } }); });
  it('exige autenticação', async () => { getSession.mockResolvedValue({ data: { session: null } }); await expect(invokeEdge('sync')).rejects.toBeInstanceOf(AuthRequiredError); expect(invoke).not.toHaveBeenCalled(); });
  it('retorna dados quando a Edge Function responde', async () => { invoke.mockResolvedValue({ data: { ok: true }, error: null }); await expect(invokeEdge('semantic-search', { body: { query: 'x' } })).resolves.toEqual({ ok: true }); });
  it('não retenta 429 e expõe retryAfter', async () => { const error = Object.assign(new Error('too many'), { context: { status: 429, headers: { get: () => '7' } } }); invoke.mockResolvedValue({ data: null, error }); await expect(invokeEdge('semantic-search')).rejects.toMatchObject({ retryAfterSec: 7 }); expect(invoke).toHaveBeenCalledTimes(1); });
  it('não retenta mutações sem chave idempotente', async () => { const error = Object.assign(new Error('server'), { context: { status: 503 } }); invoke.mockRejectedValue(error); await expect(invokeEdge('ai-ingest', { maxRetries: 1 })).rejects.toMatchObject({ status: 503 }); expect(invoke).toHaveBeenCalledTimes(1); });
  it('retenta mutações somente com chave e prova de idempotência', async () => { const error = Object.assign(new Error('server'), { context: { status: 503 } }); invoke.mockRejectedValueOnce(error).mockResolvedValue({ data: { ok: true }, error: null }); await expect(invokeEdge('ai-ingest', { maxRetries: 1, idempotencyKey: 'stable-key', isIdempotent: true })).resolves.toEqual({ ok: true }); expect(invoke).toHaveBeenCalledTimes(2); });
  it('não retenta 503 quando noRetryOnUnavailable', async () => { const error = Object.assign(new Error('unavailable'), { context: { status: 503 } }); invoke.mockResolvedValue({ data: null, error }); await expect(invokeEdge('semantic-search', { noRetryOnUnavailable: true })).rejects.toBeInstanceOf(UnavailableError); expect(invoke).toHaveBeenCalledTimes(1); });
  it('converte timeout em erro tipado', async () => { invoke.mockReturnValue(new Promise(() => undefined)); await expect(invokeEdge('fsrs-optimize', { timeoutMs: 5, maxRetries: 0 })).rejects.toBeInstanceOf(EdgeTimeoutError); });
});
